# Generated by Django 5.1.4 on 2024-12-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-price',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
